### ISSUE TITLE
Node 16

### ISSUE THREAD

**Issue by cengizhanhakan** [AkhileshNS/heroku-deploy#147]
GitHub Actions has started giving me this warning. And, I wanted to know if there are any solutions to this. Thanks, community.

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: akhileshns/heroku-deploy.`

P.S: Is this repo still being maintained? If it isn't are there any alternatives to this one?

**Comment by kaiomagalhaes** [comment]
I started seeing it as well. @cengizhanhakan I've started talking to @AkhileshNS about continuing maintenance on this repo. Hopefully further maintenance will start soon.

**Comment by AkhileshNS** [comment]
Hey @cengizhanhakan, yes as @kaiomagalhaes said, I do plan on establishing proper long-term maintenance for the action soon (within the next 2 weeks). There's a lot of work to do and I haven't been able to give the action the attention it needs due to me being stuck with a lot of academic work (I'm currently a student) so I apologize for that. But I'll make sure to get on top of things soon

**Comment by kaiomagalhaes** [comment]
Hey @AkhileshNS any updates on this?

**Comment by Saul077** [comment]
Hey @AkhileshNS, we need you man...

**Comment by andrejromanov** [comment]
+1

**Comment by andrejromanov** [comment]
@cengizhanhakan you marked this issue as completed but there haven't been any new releases since Feb 2021

**Comment by SebDanielsson** [comment]
This is still an issue :/

**Comment by cengizhanhakan** [comment]
@andrejromanov @SebDanielsson You can find the fork I have on my profile. Since @AkhileshNS has provided an answer I thought there was no reason to keep it open.
