### ISSUE TITLE
Support setting environment variables

### ISSUE THREAD

**Issue by SpencerKaiser** [AkhileshNS/heroku-deploy#17]
It would be awesome to be able to add environment variables using stored secrets in GitHub

**Comment by AkhileshNS** [comment]
That would be pretty awesome. You'd be able to store things like API Keys and stuff within GitHub itself. But I think this kind of thing would need to be it's own action (that way in can be used for more than just deploying to heroku). 

I think I have an idea on how to do this but I'm not quite sure if it'll work. I'll do some research and get back to you on this. Thanks for the suggestion

**Comment by SpencerKaiser** [comment]
So just to clarify, I was talking about using the [Heroku CLI to set env Vars](https://devcenter.heroku.com/articles/config-vars) during deploy. Aren’t you already using the CLI as part of this action? If that’s the case, all you’d need to do is support a new array in the yml like `env` which could be text or secrets from the repo’s stored secrets, loop over them, and set them before actually pushing the new code. Make sense?

The thing I’m concerned about is that setting env vars before deploy should restart the app, and I’m not sure if it’s possible to set them at the same time you deploy. Maybe there’s a way to do it via docker by including them in the image? 🤔

**Comment by AkhileshNS** [comment]
I think GitHub Actions does allow you to accept env variables by default so it might not even be necessary to add it officially. And I think it should be possible to set the variables before you deploy the code since it's just via the cli. It's worth testing all of this first though so I'll have to get back to you on this. 

Unfortunately I'm kind of busy for a week so It'll be a while before this feature can come around. Right now I'm trying to see if I can wrap this all up together with some performance improvements in a new version in the next two weeks. 

So if you need this urgently, I'd advice trying to fork the repository and adding the feature. Hopefully the code should look simple enough to help you out there but if you need any assistance, feel free to post it here. I'll try and keep active on this thread

**Comment by AkhileshNS** [comment]
Hey sorry about the delay but you can pass environment variables to Heroku via the action now. Check the updated README for more info. Hopefully this solves your problem and if it does, then please close the issue. If it doesn't then lemme know how I could help you out

**Comment by SpencerKaiser** [comment]
You are freaking awesome! That’s exactly what I was hoping for 🙌🙌 Thank you!!
