### ISSUE TITLE
Procfile release command is ignored

### ISSUE THREAD

**Issue by akaisuicchi** [AkhileshNS/heroku-deploy#43]
Hello. Thanks for this awesome action. I was facing issues commiting directly to other branch, finally this is solution I needed.

So, after reading about [how to run migrations after deploy](https://devcenter.heroku.com/articles/release-phase) I updated my Procfile, push the changes, run the action again and expect to populate my database, but did not happened.

The release command didn't run after deploy.

```bash
remote: -----> Launching...        
remote:  !     Release command declared: this new release will not be available until the command succeeds.        
remote:        Released v15        
remote:        https://***.herokuapp.com/ deployed to Heroku        
remote: 
remote: Verifying deploy... done.        
remote: Running release command...
remote: 
remote: **************************************        
remote: *     Application In Production!     *        
remote: **************************************        
remote: 
remote:  Do you really wish to run this command? (yes/no) [no]:        
remote:  > Command Canceled!        
remote: Waiting for release.... failed.        
To https://git.heroku.com/***.git
 * [new branch]      HEAD -> master
```
This is my Procfile. Does not seem to be wrong.

```
release: php artisan migrate
web: vendor/bin/heroku-php-nginx
```

I could write another step, log in to heroku and run the command but it is my least preferred solution

**Comment by AkhileshNS** [comment]
This seems to be happening because of a prompt showing up on Heroku's server when executing the release command:

![heroku-prompt](https://user-images.githubusercontent.com/21128574/96998567-4808c280-1551-11eb-9ba3-8bd54b88206c.png)

I'm not quite sure how to alleviate this from the Action's perspective since the release command happens within Heroku and I don't think there's any way to pass this prompt from the Action itself.

That said, most commands like this generally have an option like `-y` or something so you can run it on a server or a ci/cd pipeline. I don't know enough about php that I could tell if a similar option exists for the `release: php artisan migrate` command but you could try good old Stackoverflow and see if something comes up there

**Comment by akaisuicchi** [comment]
Hi, thanks for the answer. 

Because I saw that message from heroku logs the first I thought was should be heroku fault. 

But, it was my fault. I should run then command adding `--force`.
