### ISSUE TITLE
maintenance mode and scaling

### ISSUE THREAD

**Issue by jcavalieri** [AkhileshNS/heroku-deploy#55]
Hi @AkhileshNS,

If I need to turn maintenance mode on and off, and scale up and down, would you recommend I just use the run command? Like shown here: https://github.com/AkhileshNS/heroku-deploy#just-login

Thanks,
John

**Comment by AkhileshNS** [comment]
I guess for now you can go ahead and do that. (Just make sure your App is already created if you are going to do that). I've started working on a variant of the App which will focus more on allowing people to run their own heroku commands since transposing commands that already exist on the Heroku Cli to the Action everytime is starting to become pretty redundant and repetitive. 

So when that's ready, any kind of specific behaviors you need will become easier to add

**Comment by jcavalieri** [comment]
That makes a lot of sense.

I love how login and the git push just works, so please keep that!

Thanks for this plugin.

closing
