### ISSUE TITLE
Healthcheck without docker

### ISSUE THREAD

**Issue by SpencerKaiser** [AkhileshNS/heroku-deploy#57]
I'm using the action for a node.js app that doesn't use docker. The action deploys just fine (despite the README saying you need to use Docker), but it appears that the health check doesn't work... any idea if there's a way to get around that? Here's a [link to my project](https://github.com/AmericanAirlines/Hangar/blob/5597d8478db404cd74ee776702eb8a280a973874/.github/workflows/Build.yml#L38-L63) and a [link to a build](https://github.com/AmericanAirlines/Hangar/actions/runs/513781570) that passed when the healthcheck should have failed and the app should have been rolled back.

**Comment by AkhileshNS** [comment]
Hey @SpencerKaiser sorry for the late reply. As it stands right now, the healthcheck just checks if the page returns something (even if that something is some html with error info in it as is your case) which is why I think the healthcheck is passing. 

So it doesn't quite work as expected and I'm working on fixing that, but in the meantime can you switch to using the checkstring as well. Essentially return some kind of status like `working` at your healthcheck url and use the checkstring to verify it. Have a look at the documentation for more info

**Comment by SpencerKaiser** [comment]
@AkhileshNS thanks for the response and the clarification! So it doesn't check to see if a `200` is returned? In the example above, the request should have returned a `503 Service Unavailable`, so that's why I was surprised it continued. I also didn't see any confirmation that it was actually hitting that endpoint... did I miss something or is that not logged?

I'll definitely go add the `checkstring` to our pipeline 👌

**Comment by AkhileshNS** [comment]
I'll update the Action to check for status `200`.

**Comment by AkhileshNS** [comment]
Hey sorry it took a while but I've updated the action to check for status code 200 during healthchecks. Hopefully that solves your issue. Closing issue now

**Comment by SpencerKaiser** [comment]
Thanks @AkhileshNS !!!
